version: "3.5"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - $PWD:/metabase-data
      - type: bind
        source: ./database.db
        target: /metabase-data/database.db
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - metanet
networks:
  metanet:
    driver: bridge
